USE parks_and_recreation;
SELECT * FROM `shopping_processed (1)`;        
# What is total revenue generated by male vs female customer?;
SELECT gender, SUM(purchase_amount) AS REV 
FROM `shopping_processed (1)`
GROUP BY gender;

#Which customer used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM `shopping_processed (1)`
Where discount_applied= 'yes' and purchase_amount>= (SELECT AVG (purchase_amount) from `shopping_processed (1)` );

#Which are the top 5 products and highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating),2) AS avg_rat
FROM `shopping_processed (1)`
group by item_purchased 
order by AVG(review_rating) desc limit 10;

#Compare the average purchase amounts between standard and express shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM `shopping_processed (1)`
WHERE shipping_type IN ('Express','Standard')
GROUP BY shipping_type;

#Do subscribed customer spend more? Compare avg spend and total rev between subscriber and 
#non-subscribers.
SELECT subscription_status, 
count(customer_id) as total_cus,
avg(purchase_amount) as avg_spend, sum(purchase_amount) as total_rev
from `shopping_processed (1)`
group by subscription_status
order by total_rev, avg_spend desc;

#Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(AVG(discount_applied = 'Yes') * 100, 2) AS discount_rate
FROM `shopping_processed (1)`
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

#Segment customer into new, returing, loyal based on their total no. of purchases and
# show the count of each segment?

SELECT 
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 7 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS no_of_cus
FROM `shopping_processed (1)`
GROUP BY customer_segment;

#What are the top purchased products within each category?
SELECT category, item_purchased, COUNT(*) AS total_purchases
FROM `shopping_processed (1)`
GROUP BY category, item_purchased
ORDER BY category, total_purchases DESC;

# Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from `shopping_processed (1)`
where previous_purchases > 5
group by subscription_status;

#what is the revenue contribution of each group?
SELECT age_group, round(SUM(purchase_amount)) as total_revenue
from `shopping_processed (1)`
group by age_group 
order by total_revenue desc;
